
export const data = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    genres: "Drama, Crime",
    language: "en",
    user_score: 8.7,
    runtime_hour: 2,
    runtime_min: 22,
    release_date: "1994-09-23",
    vote_count: 27070
  },
  {
    "id": 2,
    "title": "The Godfather",
    "genres": "Drama, Crime",
    "language": "en",
    "user_score": 8.7,
    "runtime_hour": 2,
    "runtime_min": 55,
    "release_date": "1972-03-14",
    "vote_count": 20563
  },
  {
    "id": 3,
    "title": "The Godfather Part II",
    "genres": "Drama, Crime",
    "language": "en",
    "user_score": 8.6,
    "runtime_hour": 3,
    "runtime_min": 22,
    "release_date": "1974-12-20",
    "vote_count": 12403
  },
  {
    "id": 4,
    "title": "Schindler's List",
    "genres": "Drama, History, War",
    "language": "en",
    "user_score": 8.6,
    "runtime_hour": 3,
    "runtime_min": 15,
    "release_date": "1993-12-15",
    "vote_count": 15810
  },
  {
    "id": 5,
    "title": "12 Angry Men",
    "genres": "Drama",
    "language": "en",
    "user_score": 8.5,
    "runtime_hour": 1,
    "runtime_min": 37,
    "release_date": "1957-04-10",
    "vote_count": 8611
  },
  {
    "id": 6,
    "title": "Spirited Away",
    "genres": "Animation, Family, Fantasy",
    "language": "ja",
    "user_score": 8.5,
    "runtime_hour": 2,
    "runtime_min": 5,
    "release_date": "2001-07-20",
    "vote_count": 16462
  },
  {
    "id": 7,
    "title": "The Wild Robot",
    "genres": "Animation, Science Fiction, Family",
    "language": "en",
    "user_score": 8.5,
    "runtime_hour": 1,
    "runtime_min": 42,
    "release_date": "2024-09-12",
    "vote_count": 2593
  },
  {
    "id": 8,
    "title": "Dilwale Dulhania Le Jayenge",
    "genres": "Comedy, Drama, Romance",
    "language": "hi",
    "user_score": 8.5,
    "runtime_hour": 3,
    "runtime_min": 10,
    "release_date": "1995-10-20",
    "vote_count": 4434
  },
  {
    "id": 9,
    "title": "The Dark Knight",
    "genres": "Drama, Action, Crime, Thriller",
    "language": "en",
    "user_score": 8.5,
    "runtime_hour": 2,
    "runtime_min": 32,
    "release_date": "2008-07-16",
    "vote_count": 32816
  },
  {
    "id": 10,
    "title": "The Green Mile",
    "genres": "Fantasy, Drama, Crime",
    "language": "en",
    "user_score": 8.5,
    "runtime_hour": 3,
    "runtime_min": 9,
    "release_date": "1999-12-10",
    "vote_count": 17376
  },
  {
    "id": 11,
    title: "Parasite",
    "genres": "Comedy, Thriller, Drama",
    "language": "ko",
    "user_score": 8.5,
    "runtime_hour": 2,
    "runtime_min": 13,
    "release_date": "2019-05-30",
    "vote_count": 18215
  },
  {
    "id": 12,
    "title": "Pulp Fiction",
    "genres": "Thriller, Crime",
    "language": "en",
    "user_score": 8.5,
    "runtime_hour": 2,
    "runtime_min": 34,
    "release_date": "1994-09-10",
    "vote_count": 27853
  },
  {
    "id": 13,
    "title": "Your Name.",
    "genres": "Animation, Romance, Drama",
    "language": "ja",
    "user_score": 8.5,
    "runtime_hour": 1,
    "runtime_min": 46,
    "release_date": "2016-08-26",
    "vote_count": 11341
  },
  {
    "id": 14,
    "title": "The Lord of the Rings: The Return of the King",
    "genres": "Adventure, Fantasy, Action",
    "language": "en",
    "user_score": 8.5,
    "runtime_hour": 3,
    "runtime_min": 21,
    "release_date": "2003-12-17",
    "vote_count": 24151
  },
  {
    "id": 15,
    "title": "Forrest Gump",
    "genres": "Comedy, Drama, Romance",
    "language": "en",
    "user_score": 8.5,
    "runtime_hour": 2,
    "runtime_min": 22,
    "release_date": "1994-06-23",
    "vote_count": 27384
  },
  {
    "id": 16,
    "title": "Seven Samurai",
    "genres": "Action, Drama",
    "language": "ja",
    "user_score": 8.5,
    "runtime_hour": 3,
    "runtime_min": 27,
    "release_date": "1954-04-26",
    "vote_count": 3660
  },
  {
    "id": 17,
    "title": "The Good, the Bad and the Ugly",
    "genres": "Western",
    "language": "it",
    "user_score": 8.5,
    "runtime_hour": 2,
    "runtime_min": 41,
    "release_date": "1966-12-22",
    "vote_count": 8584
  },
  {
    "id": 18,
    "title": "GoodFellas",
    "genres": "Drama, Crime",
    "language": "en",
    "user_score": 8.5,
    "runtime_hour": 2,
    "runtime_min": 25,
    "release_date": "1990-09-12",
    "vote_count": 12824
  },
  {
    "id": 19,
    "title": "Grave of the Fireflies",
    "genres": "Animation, Drama, War",
    "language": "ja",
    "user_score": 8.5,
    "runtime_hour": 1,
    "runtime_min": 29,
    "release_date": "1988-04-16",
    "vote_count": 5536
  },
  {
    "id": 20,
    "title": "Cinema Paradiso",
    "genres": "Drama, Romance",
    "language": "it",
    "user_score": 8.5,
    "runtime_hour": 2,
    "runtime_min": 4,
    "release_date": "1988-11-17",
    "vote_count": 4354
  },
  {
    "id": 21,
    "title": "Life Is Beautiful",
    "genres": "Comedy, Drama",
    "language": "it",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 56,
    "release_date": "1997-12-20",
    "vote_count": 12998
  },
  {
    "id": 22,
    "title": "Interstellar",
    "genres": "Adventure, Drama, Science Fiction",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 49,
    "release_date": "2014-11-05",
    "vote_count": 35515
  },
  {
    "id": 23,
    "title": "Fight Club",
    "genres": "Drama",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 19,
    "release_date": "1999-10-15",
    "vote_count": 29324
  },
  {
    "id": 24,
    "title": "Impossible Things",
    "genres": "Family, Drama",
    "language": "es",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 28,
    "release_date": "2021-06-17",
    "vote_count": 387
  },
  {
    "id": 25,
    "title": "Psycho",
    "genres": "Horror, Thriller, Mystery",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 49,
    "release_date": "1960-06-22",
    "vote_count": 10027
  },
  {
    "id": 26,
    "title": "City of God",
    "genres": "Drama, Crime",
    "language": "pt",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 9,
    "release_date": "2002-08-30",
    "vote_count": 7361
  },
  {
    "id": 27,
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "genres": "Adventure, Fantasy, Action",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 59,
    "release_date": "2001-12-18",
    "vote_count": 25089
  },
  {
    "id": 28,
    "title": "One Flew Over the Cuckoo's Nest",
    "genres": "Drama",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 13,
    "release_date": "1975-11-19",
    "vote_count": 10402
  },
  {
    "id": 29,
    "title": "Once Upon a Time in America",
    "genres": "Drama, Crime",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 3,
    "runtime_min": 49,
    "release_date": "1984-05-23",
    "vote_count": 5368
  },
  {
    "id": 30,
    "title": "Gabriel's Inferno",
    "genres": "Romance, Drama",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 2,
    "release_date": "2020-05-29",
    "vote_count": 2410
  },
  {
    "id": 31,
    "title": "A Dog's Will",
    "genres": "Comedy, Drama, Fantasy",
    "language": "pt",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 44,
    "release_date": "2000-09-15",
    "vote_count": 1093
  },
  {
    "id": 32,
    "title": "Harakiri",
    "genres": "Action, Drama, History",
    "language": "ja",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 15,
    "release_date": "1962-09-15",
    "vote_count": 990
  },
  {
    "id": 33,
    "title": "Primal: Tales of Savagery",
    "genres": "Action, Adventure, Animation, Drama",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 25,
    "release_date": "2019-11-21",
    "vote_count": 315
  },
  {
    "id": 34,
    "title": "Howl's Moving Castle",
    "genres": "Fantasy, Animation, Adventure",
    "language": "ja",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 59,
    "release_date": "2004-09-09",
    "vote_count": 9852
  },
  {
    "id": 35,
    "title": "The Lord of the Rings: The Two Towers",
    "genres": "Adventure, Fantasy, Action",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 59,
    "release_date": "2002-12-18",
    "vote_count": 21798
  },
  {
    "id": 36,
    "title": "Spider-Man: Into the Spider-Verse",
    "genres": "Animation, Action, Adventure, Science Fiction",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 57,
    "release_date": "2018-12-06",
    "vote_count": 15552
  },
  {
    "id": 37,
    "title": "Hope",
    "genres": "Drama",
    "language": "ko",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 2,
    "release_date": "2013-10-02",
    "vote_count": 729
  },
  {
    "id": 38,
    "title": "The Empire Strikes Back",
    "genres": "Adventure, Action, Science Fiction",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 4,
    "release_date": "1980-05-20",
    "vote_count": 16887
  },
  {
    "id": 39,
    "title": "Gabriel's Inferno: Part II",
    "genres": "Romance, Drama",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 45,
    "release_date": "2020-07-31",
    "vote_count": 1513
  },
  {
    "id": 40,
    "title": "Dou kyu sei – Classmates",
    "genres": "Romance, Animation",
    "language": "ja",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 1,
    "release_date": "2016-02-20",
    "vote_count": 382
  },
  {
    "id": 41,
    "title": "Gabriel's Inferno: Part III",
    "genres": "Romance, Drama",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 45,
    "release_date": "2020-11-19",
    "vote_count": 1053
  },
  {
    "id": 42,
    "title": "A Silent Voice: The Movie",
    "genres": "Animation, Drama",
    "language": "ja",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 9,
    "release_date": "2016-09-17",
    "vote_count": 3938
  },
  {
    "id": 43,
    "title": "Whiplash",
    "genres": "Drama, Music",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 47,
    "release_date": "2014-10-10",
    "vote_count": 15034
  },
  {
    "id": 44,
    "title": "The Pianist",
    "genres": "Drama, War",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 30,
    "release_date": "2002-09-17",
    "vote_count": 9136
  },
  {
    "id": 45,
    "title": "Se7en",
    "genres": "Crime, Mystery, Thriller",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 7,
    "release_date": "1995-09-22",
    "vote_count": 20934
  },
  {
    "id": 46,
    "title": "Radical",
    "genres": "Drama",
    "language": "es",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 6,
    "release_date": "2023-10-19",
    "vote_count": 416
  },
  {
    "id": 47,
    "title": "Inception",
    "genres": "Action, Science Fiction, Adventure",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 28,
    "release_date": "2010-07-15",
    "vote_count": 36495
  },
  {
    "id": 48,
    "title": "The Legend of Hei",
    "genres": "Animation, Fantasy, Action",
    "language": "zh",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 42,
    "release_date": "2019-08-27",
    "vote_count": 364
  },
  {
    "id": 49,
    "title": "Spider-Man: Across the Spider-Verse",
    "genres": "Animation, Action, Adventure, Science Fiction",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 20,
    "release_date": "2023-05-31",
    "vote_count": 6915
  },
  {
    "id": 50,
    "title": "TAYLOR SWIFT | THE ERAS TOUR",
    "genres": "Music",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 2,
    "runtime_min": 49,
    "release_date": "2023-10-13",
    "vote_count": 397
  },
  {
    "id": 51,
    "title": "Rear Window",
    "genres": "Thriller, Mystery",
    "language": "en",
    "user_score": 8.4,
    "runtime_hour": 1,
    "runtime_min": 52,
    "release_date": "1954-08-01",
    "vote_count": 6453
  },
  {
    "id": 52,
    "title": "The Silence of the Lambs",
    "genres": "Crime, Drama, Thriller",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 59,
    "release_date": "1991-02-14",
    "vote_count": 16228
  },
  {
    "id": 53,
    "title": "Taylor Swift: Reputation Stadium Tour",
    "genres": "Music",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 5,
    "release_date": "2018-12-31",
    "vote_count": 382
  },
  {
    "id": 54,
    "title": "American History X",
    "genres": "Drama",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 59,
    "release_date": "1998-07-01",
    "vote_count": 11497
  },
  {
    "id": 55,
    "title": "Princess Mononoke",
    "genres": "Adventure, Fantasy, Animation",
    "language": "ja",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 14,
    "release_date": "1997-07-12",
    "vote_count": 7969
  },
  {
    "id": 56,
    "title": "High and Low",
    "genres": "Drama, Crime, Mystery",
    "language": "ja",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 22,
    "release_date": "1963-03-01",
    "vote_count": 900
  },
  {
    "id": 57,
    "title": "The Quintessential Quintuplets Movie",
    "genres": "Animation, Comedy, Romance",
    "language": "ja",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 16,
    "release_date": "2022-05-20",
    "vote_count": 382
  },
  {
    "id": 58,
    "title": "A Brighter Summer Day",
    "genres": "Crime, Drama, Romance",
    "language": "zh",
    "user_score": 8.3,
    "runtime_hour": 3,
    "runtime_min": 57,
    "release_date": "1991-07-27",
    "vote_count": 314
  },
  {
    "id": 59,
    "title": "Back to the Future",
    "genres": "Adventure, Comedy, Science Fiction",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 56,
    "release_date": "1985-07-03",
    "vote_count": 19840
  },
  {
    "id": 60,
    "title": "Once Upon a Studio",
    "genres": "Animation, Family, Fantasy, Comedy",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 0,
    "runtime_min": 9,
    "release_date": "2023-09-24",
    "vote_count": 352
  },
  {
    "id": 61,
    "title": "Perfect Blue",
    "genres": "Animation, Thriller",
    "language": "ja",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 22,
    "release_date": "1998-02-28",
    "vote_count": 2633
  },
  {
    "id": 62,
    "title": "Hotarubi no Mori e",
    "genres": "Romance, Animation, Fantasy",
    "language": "ja",
    "user_score": 8.3,
    "runtime_hour": 0,
    "runtime_min": 45,
    "release_date": "2011-09-17",
    "vote_count": 1101
  },
  {
    "id": 63,
    "title": "Sunset Boulevard",
    "genres": "Drama",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 50,
    "release_date": "1950-08-10",
    "vote_count": 2561
  },
  {
    "id": 64,
    "title": "Dead Poets Society",
    "genres": "Drama",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 8,
    "release_date": "1989-06-02",
    "vote_count": 11204
  },
  {
    "id": 65,
    "title": "Léon: The Professional",
    "genres": "Crime, Drama, Action",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 51,
    "release_date": "1994-09-14",
    "vote_count": 14719
  },
  {
    "id": 66,
    "title": "Dedicated to my ex",
    "genres": "Drama, Comedy",
    "language": "es",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 34,
    "release_date": "2019-11-01",
    "vote_count": 501
  },
  {
    "id": 67,
    "title": "The Great Dictator",
    "genres": "Comedy, War",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 5,
    "release_date": "1940-10-15",
    "vote_count": 3353
  },
  {
    "id": 68,
    "title": "The Count of Monte-Cristo",
    "genres": "Action, Adventure, Drama, History, Romance, Thriller",
    "language": "fr",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 58,
    "release_date": "2024-06-28",
    "vote_count": 772
  },
  {
    "id": 69,
    "title": "Neon Genesis Evangelion: The End of Evangelion",
    "genres": "Animation, Science Fiction, Action, Drama",
    "language": "ja",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 27,
    "release_date": "1997-07-19",
    "vote_count": 1590
  },
  {
    "id": 70,
    "title": "Ikiru",
    "genres": "Drama",
    "language": "ja",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 23,
    "release_date": "1952-10-09",
    "vote_count": 1126
  },
  {
    "id": 71,
    "title": "Modern Times",
    "genres": "Comedy, Drama, Romance",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 27,
    "release_date": "1936-02-05",
    "vote_count": 3676
  },
  {
    "id": 72,
    "title": "Once Upon a Time in the West",
    "genres": "Drama, Western",
    "language": "it",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 46,
    "release_date": "1968-12-21",
    "vote_count": 4312
  },
  {
    "id": 73,
    "title": "City Lights",
    "genres": "Comedy, Drama, Romance",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 27,
    "release_date": "1931-02-06",
    "vote_count": 2152
  },
  {
    "id": 74,
    "title": "The Intouchables",
    "genres": "Drama, Comedy",
    "language": "fr",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 53,
    "release_date": "2011-11-02",
    "vote_count": 17150
  },
  {
    "id": 75,
    "title": "Apocalypse Now",
    "genres": "Drama, War",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 27,
    "release_date": "1979-08-15",
    "vote_count": 8184
  },
  {
    "id": 76,
    "title": "It's a Wonderful Life",
    "genres": "Drama, Family, Fantasy",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 10,
    "release_date": "1946-12-20",
    "vote_count": 4256
  },
  {
    "id": 77,
    "title": "Violet Evergarden: The Movie",
    "genres": "Animation, Fantasy, Romance, Drama",
    "language": "ja",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 20,
    "release_date": "2020-09-18",
    "vote_count": 404
  },
  {
    "id": 78,
    "title": "Paths of Glory",
    "genres": "War, Drama, History",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 28,
    "release_date": "1957-10-25",
    "vote_count": 2886
  },
  {
    "id": 79,
    "title": "The Boy, the Mole, the Fox and the Horse",
    "genres": "Animation, Family, Adventure, Fantasy",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 0,
    "runtime_min": 35,
    "release_date": "2022-12-25",
    "vote_count": 565
  },
  {
    "id": 80,
    "title": "Josee, the Tiger and the Fish",
    "genres": "Animation, Drama, Romance",
    "language": "ja",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 38,
    "release_date": "2020-12-25",
    "vote_count": 462
  },
  {
    "id": 81,
    "title": "Miracle in Cell No. 7",
    "genres": "Drama",
    "language": "tr",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 12,
    "release_date": "2019-10-10",
    "vote_count": 4392
  },
  {
    "id": 82,
    "title": "Given",
    "genres": "Animation, Drama, Music, Romance",
    "language": "ja",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 0,
    "release_date": "2020-08-22",
    "vote_count": 377
  },
  {
    "id": 83,
    "title": "The Legend of 1900",
    "genres": "Drama, Music",
    "language": "it",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 50,
    "release_date": "1998-10-28",
    "vote_count": 2238
  },
  {
    "id": 84,
    "title": "Le Trou",
    "genres": "Drama, Thriller, Crime",
    "language": "fr",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 12,
    "release_date": "1960-03-18",
    "vote_count": 469
  },
  {
    "id": 85,
    "title": "We All Loved Each Other So Much",
    "genres": "Drama, Comedy",
    "language": "it",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 4,
    "release_date": "1974-12-21",
    "vote_count": 548
  },
  {
    "id": 86,
    "title": "Clouds",
    "genres": "Music, Drama, Romance",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 1,
    "release_date": "2020-10-09",
    "vote_count": 1002
  },
  {
    "id": 87,
    "title": "The Lion King",
    "genres": "Family, Animation, Drama",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 29,
    "release_date": "1994-06-24",
    "vote_count": 18209
  },
  {
    "id": 88,
    "title": "Oldboy",
    "genres": "Drama, Thriller, Mystery, Action",
    "language": "ko",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 0,
    "release_date": "2003-11-21",
    "vote_count": 8630
  },
  {
    "id": 89,
    "title": "Life in a Year",
    "genres": "Drama, Romance",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 47,
    "release_date": "2020-11-27",
    "vote_count": 1872
  },
  {
    "id": 90,
    "title": "Five Feet Apart",
    "genres": "Romance, Drama",
    "language": "en",
    "user_score": 8.3,
    "runtime_hour": 1,
    "runtime_min": 56,
    "release_date": "2019-03-14",
    "vote_count": 5581
  },
  {
    "id": 91,
    "title": "Come and See",
    "genres": "Drama, War",
    "language": "ru",
    "user_score": 8.3,
    "runtime_hour": 2,
    "runtime_min": 22,
    "release_date": "1985-10-17",
    "vote_count": 1475
  },
  {
    "id": 92,
    "title": "Avengers: Endgame",
    "genres": "Adventure, Science Fiction, Action",
    "language": "en",
    "user_score": 8.2,
    "runtime_hour": 3,
    "runtime_min": 1,
    "release_date": "2019-04-24",
    "vote_count": 25551
  },
  {
    "id": 93,
    "title": "Evangelion: 3.0+1.0 Thrice Upon a Time",
    "genres": "Animation, Action, Science Fiction, Drama",
    "language": "ja",
    "user_score": 8.2,
    "runtime_hour": 2,
    "runtime_min": 35,
    "release_date": "2021-03-08",
    "vote_count": 806
  },
  {
    "id": 94,
    "title": "Avengers: Infinity War",
    "genres": "Adventure, Action, Science Fiction",
    "language": "en",
    "user_score": 8.2,
    "runtime_hour": 2,
    "runtime_min": 29,
    "release_date": "2018-04-25",
    "vote_count": 29662
  },
  {
    "id": 95,
    "title": "Klaus",
    "genres": "Animation, Family, Adventure, Comedy, Fantasy",
    "language": "en",
    "user_score": 8.2,
    "runtime_hour": 1,
    "runtime_min": 36,
    "release_date": "2019-11-08",
    "vote_count": 3979
  },
  {
    "id": 96,
    "title": "Green Book",
    "genres": "Drama, History",
    "language": "en",
    "user_score": 8.2,
    "runtime_hour": 2,
    "runtime_min": 10,
    "release_date": "2018-11-16",
    "vote_count": 11527
  },
  {
    "id": 97,
    "title": "Mommy",
    "genres": "Drama",
    "language": "fr",
    "user_score": 8.2,
    "runtime_hour": 2,
    "runtime_min": 18,
    "release_date": "2014-09-19",
    "vote_count": 2702
  },
  {
    "id": 98,
    "title": "Rascal Does Not Dream of a Dreaming Girl",
    "genres": "Animation, Romance, Drama, Fantasy",
    "language": "ja",
    "user_score": 8.2,
    "runtime_hour": 1,
    "runtime_min": 30,
    "release_date": "2019-06-15",
    "vote_count": 520
  },
  {
    "id": 99,
    "title": "Wolf Children",
    "genres": "Animation, Family, Drama, Fantasy",
    "language": "ja",
    "user_score": 8.2,
    "runtime_hour": 1,
    "runtime_min": 57,
    "release_date": "2012-07-21",
    "vote_count": 2275
  },
  {
    "id": 100,
    "title": "Wolfwalkers",
    "genres": "Animation, Family, Adventure, Fantasy",
    "language": "en",
    "user_score": 8.2,
    "runtime_hour": 1,
    "runtime_min": 43,
    "release_date": "2020-10-26",
    "vote_count": 1182
  },
]